// Extracts the compiled contract ABI into committed, consumable files:
//   - abi/FoodTraceability.json                 (canonical artifact)
//   - frontend/src/abi/foodTraceability.ts      (typed `as const` for wagmi)
// Run via `npm run export:abi` (compiles first, then writes both).
const fs = require("fs");
const path = require("path");

const artifact = require("../artifacts/contracts/FoodTraceability.sol/FoodTraceability.json");
const root = path.join(__dirname, "..");

function write(file, contents) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, contents);
  console.log(`ABI written to ${path.relative(root, file)}`);
}

const json = JSON.stringify(artifact.abi, null, 2);

write(path.join(root, "abi", "FoodTraceability.json"), json + "\n");

write(
  path.join(root, "frontend", "src", "abi", "foodTraceability.ts"),
  `// AUTO-GENERATED by scripts/exportAbi.js — do not edit by hand.\n` +
    `export const foodTraceabilityAbi = ${json} as const;\n`,
);
